Remove support for 2.6, 3.2, and 3.3.
Because I am sick of dealing with stuff like:

    ======================================================================
    ERROR: Failure: SyntaxError (invalid syntax (pyopenssl.py, line 169))
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nose/loader.py", line 414, in loadTestsFromName
        addr.filename, addr.module)
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/home/travis/build/sprockets/sprockets.mixins.sentry/sprockets/mixins/sentry/__init__.py", line 21, in <module>
        import raven
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/raven/__init__.py", line 54, in <module>
        from raven.base import *  # NOQA
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/raven/base.py", line 34, in <module>
        from raven.conf.remote import RemoteConfig
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/raven/conf/remote.py", line 36, in <module>
        DEFAULT_TRANSPORT = discover_default_transport()
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/raven/conf/remote.py", line 18, in discover_default_transport
        from raven.transport.threaded import ThreadedHTTPTransport
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/raven/transport/__init__.py", line 17, in <module>
        from raven.transport.requests import *  # NOQA
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/raven/transport/requests.py", line 13, in <module>
        import requests
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/requests/__init__.py", line 52, in <module>
        from .packages.urllib3.contrib import pyopenssl
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 169
        for prefix in [u'*.', u'.']:
                           ^
    SyntaxError: invalid syntax